#path to the log file
logging: "/var/log/wp_py.log"

#list of webserver variables, folder and user/group
www:
 www_path: "/var/www/html/wordpress"
 www_user: "www-data"
 www_group: "www-data"

#List of the database params
database:
 database:   #variables to connect the DB
  ip_address: localhost
  db_admin: wordpress
  db_password: wordpress
  db_name: wordpress
  db_port: 3306
  unix_sock: "/var/run/mysqld/mysqld.sock"
 query:  #queries to configure and create the DB
  - "create database wordpress;"
  - "create user 'wordpress'@'localhost' identified by 'wordpress';"
  - "grant all on magento.* to 'wordpress'@'localhost' identified by 'wordpress' with grant option;"
  - "flush privileges;"

#List of required packages case sensitive with apt package name
packages:
 - apache2
 - mariadb-server
 - gnupg
 - lsb-release
 - apt-transport-https
 - ca-certificates

#list of commands for each component
commands:
 ssl:
  - mkdir -p /etc/apache2/ssl
  - openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/apache2/ssl/apache.key -out /etc/apache2/ssl/apache.crt --config config_files/cert.cnf
  - chmod -R 600 /etc/apache2/ssl
 apache2_mods:
  - a2enmod ssl
  - a2ensite default-ssl
  - a2enmod rewrite
  - a2enmod expires
  - a2enmod headers
  - a2enmod proxy
  - a2enmod proxy_html
 php74:
  - wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
  - echo "deb https://packages.sury.org/php $(lsb_release -sc) main" | suto tee /etc/apt/sources.list.d/php.list
  - apt update
 apache2_end:
  - chown -R  /var/www/html/wordpress
  - systemctl restart apache2
 wp_inst:
  - mkdir -p /var/www/html/wordpress
  - wget -O /tmp/wp-cli.phar https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - chmod +x /tmp/wp-cli.phar
  - cp /tmp/wp-cli.phar /usr/local/bin/wp
  - wp cli update
  - chown -R www-data:www-data /var/www/html/wordpress
#  - cd /var/www/html/wordpress
  - sudo -u www-data wp core download cwd=/var/www/html/wordpress
  - sudo -u www-data wp core config --dbname=wordpress dbuser=wordpress --dbpass=wordpress
  - sudo -u www-data wp core install --url=https://192.168.1.15 --title=WPfromscript --admin_user=admin --admin_password=admin --admin_email=admin@local.net

#list of files for modification
files:
 apache_ssl_cert:
  file: "/etc/apache2/sites-available/default-ssl.conf" 
  string: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
  new_string: "/etc/apache2/ssl/apache.crt"
 apache_ssl_key:
  file: "/etc/apache2/sites-available/default-ssl.conf"
  string: "/etc/ssl/private/ssl-cert-snakeoil.key"
  new_string: "/etc/apache2/ssl/apache.key"
 apache_vhost_wp:
  file: "/etc/apache2/sites-available/default-ssl.conf"
  string: "DocumentRoot /var/www/html"  
  new_string: "DocumentRoot /var/www/html/wordpress\n\t\t<Directory /var/www/html/wordpress>\n\t\t\tAllowOverride All\n\t\t</Directory>"

#List of options and values for magento install
magento_setup:
 admin-firstname: admin
 admin-lastname: magento
 language: fr_FR
 currency: EUR
 timezone: Europe/Paris
 use-secure: "1"
 base-url-secure: https://192.168.1.13
 db-host: localhost
 db-user: magento
 db-password: magento
 db-name: magento
 use-secure-admin: "1"
 admin-password: passw0rd
 admin-email: admin@local.net
 base-url: https://192.168.1.13
 admin-user: admin
